# Exclude paths from formatting
exclude = ["target/**", ".direnv/**", ".git/**"]

[formatting]
indent_style = "space"
indent_size = 2

[[rule]]
include = ["**/Cargo.toml"]
keys = [
  "dependencies",
  "dev-dependencies",
  "build-dependencies",
  "workspace.dependencies",
]
[rule.formatting]
reorder_keys = true
align_comments = true

[[rule]]
include = ["**/Cargo.toml"]
keys = ["package", "features", "lib", "package.metadata", "package.metadata.*"]
[rule.formatting]
reorder_keys = true
