[package]
name = "payjoin-cli"
version = "0.0.1"
authors = ["Dan Gould <d@ngould.dev>", "Martin Habovstiak <martin.habovstiak@gmail.com>"]
edition = "2018"

[[bin]]
name = "payjoin"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
reelay = ["tungstenite", "url"]
native-tls-vendored = ["reqwest/native-tls-vendored"]

[dependencies]
anyhow = "1.0.70"
base64 = "0.13.0"
bip21 = "0.3.1"
bitcoincore-rpc = "0.17.0"
clap = "4.1.4"
config = "0.13.3"
env_logger = "0.9.0"
log = "0.4.7"
payjoin = { path = "../payjoin", features = ["send", "receive"] }
reqwest = { version = "0.11.4", features = ["blocking"] }
rouille = "3.6.1"
serde = { version = "1.0.160", features = ["derive"] }
tungstenite = { version = "0.19.0", optional = true }
url = {version= "2.3.1", optional = true}
