[package]
name = "payjoin-relay"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
futures-util = { version = "0.3.28", default-features = false, features = ["sink", "std"] }
payjoin = { path = "../payjoin", features = ["v2"] }
tokio = { version = "1.12.0", features = ["full"] }
tokio-tungstenite = "0.20.0"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
