[package]
name = "payjoin-relay"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.28"
hyper = { version = "0.14.26", features = ["server"] }
tokio = { version = "1.28.2", features = ["full"] }
tungstenite = "0.19.0"
tokio-tungstenite = "*"