name: Test and Build

on: [push, pull_request]

jobs:

  test-lib:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: payjoin
    strategy:
      fail-fast: false
      matrix:
        rust:
          - 1.57.0 # MSRV
          - stable
          - nightly

    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1.2.0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Fixes for MSRV
        if: matrix.rust == '1.57.0'
        run: |
          cargo update
          cargo update -p log --precise 0.4.18
          cargo update -p tempfile --precise 3.6.0
          cargo update -p flate2 --precise 1.0.26
          cargo update -p rustls --precise 0.20.8
      - name: test
        run: cargo test --verbose --all-features --lib

  build-payjoin-cli:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: payjoin-cli
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, nightly]

    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1.2.0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - name: build payjoin cli example
        run: |
          cargo build

  fmt:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        package: [payjoin, payjoin-cli]

    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1.2.0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - run: rustup component add rustfmt --toolchain nightly-x86_64-unknown-linux-gnu
      - name: fmt check
        run: |
          cd ${{ matrix.package }}
          cargo fmt --all -- --check
